### ISSUE TITLE
Can't calculate price with a negative yield

### ISSUE THREAD

**Issue by thatsjohnson** [fsprojects/ExcelFinancialFunctions#13]
### Description

Can't calculate price with a negative yield. This matches current Excel capabilities, but this is a valid calculation for computing price of a bond. 

### Repro steps

Please provide the steps required to reproduce the problem

1. Call Calculators.CalcPrice(settlement, maturity, coupon, yield, 100), using a negative yield value (-0.002)

### Expected behavior

return value of Price.
http://www.investopedia.com/ask/answers/06/negativeyieldbond.asp

### Actual behavior

Exception thrown: 'System.Exception' in ExcelFinancialFunctions.dll
Additional information: yld must be more than 0

### Known workarounds

None.

### Related information 

* Windows 10
* Master Branch
* .NET Runtime

**Comment by luajalla** [comment]
Hi @thatsjohnson, would submitting a PR be an option for you? I'd be glad to merge it, but can't promise I'll be able to find time for a fix in the nearest future...

Thanks,
Natallie

**Comment by jcoliz** [comment]
Labeling as "enhancement", as current behavior meets the stated goal of matching excel behavior. However, I can see how it would be useful to additionally cover this situation.

**Comment by jcoliz** [comment]
@thatsjohnson , Hi I know it's been a long time since you filed this. If you're still interested, would you mind trying out the issue-13 branch? https://github.com/fsprojects/ExcelFinancialFunctions/tree/feature/issue-13 . I created a new API "PriceAllowNegativeYield" which is just the old "Price" API with the yield > 0 check removed. It would be interesting to see if this gives the results you expect.

**Comment by jcoliz** [comment]
Update: I did manage to create a 10,000-item data set in Excel, following the spirit of the other tests. Spot checks of that data set passed, so I believe this change is correct. Still to do, need to create a test like the other large data set tests to be sure.

**Comment by thatsjohnson** [comment]
Thank you. Will check it out.
