### ISSUE TITLE
Generating Documentation

### ISSUE THREAD

**Issue by russlamb** [fsprojects/ExcelFinancialFunctions#16]
### Description

I cannot find documentation on the library, nor is there any documentation on how to generate the documentation.

### Repro steps

1. The API Reference link is broken.  It produces an empty page.  http://fsprojects.github.io/ExcelFinancialFunctions/reference/index.html

2. The "/docs/content" folder has some text files that say there is a way to generate documentation but no instructions on how to do so.

### Expected behavior

I would expect a way to generate / view documentation

### Actual behavior

Current links are broken, not instrucitons on generating docs.

### Related information 

* Operating system: Windows 7
* Branch: master
* .NET Runtime, CoreCLR or Mono Version: All
* Performance information, links to performance testing scripts: N/A

**Comment by dsyme** [comment]
@russlamb I took a look out of curiosity.  I think the problem with reference documentation generation is that this library builds a .NET Portable assembly, and the documentation generation technique is unable to generate reference documentation from this as implemented.

The assembly-loading approach used by generate.fsx is problematic and needs to be fixed systematically across quite a number of projects.

**Comment by luajalla** [comment]
@dsyme, thanks for looking into this! How is this generally solved in other projects? Maybe we could switch from portable assembly to something else, it doesn't seem to work for everyone as it is now anyway.

**Comment by jcoliz** [comment]
@dsyme is there another project that has solved it well in the ensuing years? Would like to fix this, but I've no clue about how this works. Would be nice to have a working model to follow.

**Comment by jcoliz** [comment]
Ok, PR #46 has been merged. http://fsprojects.github.io/ExcelFinancialFunctions gives a 404. What's next?

**Comment by jcoliz** [comment]
Ok, I did find the setting under the repo to publish gh-pages. The root looks ok now. However, some links, e.g. "API reference" immediately redirect to an HTTPS link, and then layout problems follow.

```
Blocked loading mixed active content “http://fsprojects.github.io/ExcelFinancialFunctions/content/navbar-fixed-left.css”
index.html
Blocked loading mixed active content “http://fsprojects.github.io/ExcelFinancialFunctions/content/fsdocs-default.css”
index.html
Blocked loading mixed active content “http://fsprojects.github.io/ExcelFinancialFunctions/content/fsdocs-custom.css”
index.html
Blocked loading mixed active content “http://fsprojects.github.io/ExcelFinancialFunctions/content/fsdocs-tips.js”
```

**Comment by nhirschey** [comment]
I’m not seeing a 404. I think your workflow fixes solved it. Looks great!

**Comment by jcoliz** [comment]
Ok, right, it's working now. I had to clear my browser cache to avoid the https preference. I posit that fsdocs has a problem with https, but that's an issue for another repo, I think.
