### ISSUE TITLE
Compilation error on local machine

### ISSUE THREAD

**Issue by kalypto-ajay** [fsprojects/ExcelFinancialFunctions#18]
Have downloaded the code and trying to compile from the command prompt using the batch file as I don't have vs 2015 installed (although, could open the project in vs 2013).

While compiling from command below is the error shown:

  1) Building D:\Sandbox\ExcelFinancialFunctions\ExcelFinancialFunctions.sln failed with exitcode 1.
  2) FS0078: D:\Sandbox\ExcelFinancialFunctions\src\ExcelFinancialFunctions\unknown(1,1): Unable to find the file 'System.Runtime.InteropServices.dll' in any of C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile259 D:\Sandbox\ExcelFinancialFunctions\src\ExcelFinancialFunctions D:\Sandbox\ExcelFinancialFunctions\packages\FSharp.Core\lib\portable-net45+netcore45+wpa81+wp8

This folder (C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile259) exists but the dll is missing.

Please help me out as have to make nuget pkg without any dependency to use in 4.5.1 web project. have seen the nuget gallery but is dependent on FSharp.Core

**Comment by luajalla** [comment]
Hi, which version of .NET is available on your machine? You don't have to reference portable assemblies, just pick them from the location with .NET version you need (both FSharp.Core and InteropServices). 

Take a look at .fsproj files for .NET 4.0 [here](https://github.com/fsprojects/ExcelFinancialFunctions/tree/2e9d9b1f22503af9f1b2a4d503ff3cbf06455e2c/src/ExcelFinancialFunctions).

**Comment by anandvadul** [comment]
I just downloaded and successfully compiled.
The error you are getting says it is looking for System.Runtime.InteropServices.dll Can you download that using your Visual Studio 2013?

Here is a helpful link that explains the steps in case you have not done it before: [using-nuget-with-visual-studio-2013](https://www.intertech.com/Blog/using-nuget-with-visual-studio-2013/)

**Comment by jcoliz** [comment]
Hi, the build has recently changed to be completely dotnet-based. Please try again with a recent build, and let us know if any issues. Thanks!
