### ISSUE TITLE
FSharp.Core 4.3.4 Nuget update

### ISSUE THREAD

**Issue by vkirienko** [fsprojects/ExcelFinancialFunctions#21]
Hi,

I'm trying to update FSharp.Core to 4.3.4 version using Nuget and getting error below.

Unable to resolve dependencies. 'FSharp.Core 4.3.4' is not compatible with 'ExcelFinancialFunctions 2.4.0 constraint: FSharp.Core (>= 4.0.0.1 && < 4.0.1)'.

Maybe it is good idea to relax upper version requirement?

Regards,
Vlad Kirienko

**Comment by luajalla** [comment]
Hi Vlad,
Thanks for reporting this. Could you please create a PR? It will probably work with the new version, but needs a quick test...

Cheers,
Natallie

**Comment by Thorium** [comment]
Yes, this is very restrictive, NuGet.org says "FSharp.Core (>= 4.0.0.1 && < 4.0.1)".
It does work with later versions also, if the Nuget package wouldn't have that.

**Comment by jcoliz** [comment]
A PR to address this issue has been merged.
