### ISSUE TITLE
Rate function throws an exception

### ISSUE THREAD

**Issue by cms** [fsprojects/ExcelFinancialFunctions#4]
Hello,

The following Rate function call results in an exception, while the behavior in Excel is to return the value _0.00043296_:

```
Financial.Rate(260,-60, 13500, 1400, 0);
```

**Exception Message:** FindBounds: one of the values (-1.000000, 3.211696) cannot be used to evaluate the objective function

**Stack trace:**

```
at Excel.FinancialFunctions.Common.rfindBounds@59(FSharpFunc`2 f, Double minBound, Double maxBound, Double precision, Double low, Double up, Int32 tries)
at Excel.FinancialFunctions.Common.findBounds(FSharpFunc`2 f, Double guess, Double minBound, Double maxBound, Double precision)
at Excel.FinancialFunctions.Common.findRoot(FSharpFunc`2 f, Double guess)
```

I'm using the version **2.2.0** from NuGet.

Thanks,

-cms

**Comment by luajalla** [comment]
Excel uses a different root-finding algo, so it's not guaranteed that the results are the same for the functions like ````Rate```` (there're other differences [too](http://fsprojects.github.io/ExcelFinancialFunctions/compatibility.html)).

When the approximate rates are known, it's always better to specify ````guess```` parameter. The library default guess is 0.1, which is too far from the expected value in this case and the lib doesn't find the root (we could increase the number of iterations, but that would be slower). Here that might be 0.04 or 0.05 or even 0.06.
Note, that in general case you won't get the same results as in Excel anyway

````Financial.Rate(260.0,-60.0, 13500.0, 1400.0, PaymentDue.BeginningOfPeriod, 0.04)````

Alternatively, you can use any solver to find the rate from ````FV(r,...) - fv = 0````

Probably, it makes sense to adjust the algo, but hard to say what the library defaults should be.

**Comment by jcoliz** [comment]
Hi, I'm cleaning up old issues. From luajalla's comments, it seems that this issue is by design. And the behavior is covered in the docs. I don't expect any further change here, so closing.
