### ISSUE TITLE
Rate > 0 required for yield

### ISSUE THREAD

**Issue by cpell** [fsprojects/ExcelFinancialFunctions#5]
I understand that there are differences between the way the library and Excel perform some calculations, however, I'm not seeing any reason an exception should be thrown when the coupon is 0. The requirement on Excel's yield function is that the rate parameter is greater than or equal to 0.

**Comment by luajalla** [comment]
Yes, I'd also say that makes sense. I'll try to find some time to take a look at it in the nearest future... unless you'd like to submit a pull request yourself )

**Comment by cpell** [comment]
https://github.com/fsprojects/ExcelFinancialFunctions/pull/6

**Comment by luajalla** [comment]
Thank you for the contribution!
