### ISSUE TITLE
Yields do not match Excel with certain parameters

### ISSUE THREAD

**Issue by cpell** [fsprojects/ExcelFinancialFunctions#7]
Almost every calculation I have tried matches Excel, but I have a few such as the following which are way off and I'm not sure why

Yield("09/19/2014","10/20/2014",5.25/100,100.171,100,2,2) = 0.031569 Yield("09/09/2014","10/20/2014",5.25/100,100.305,100,2,2) = 0.024695 

    Financial.Yield(new DateTime(2014,09,19), new DateTime(2014,10,20), 5.25/100, 100.171, 100, Frequency.SemiAnnual, DayCountBasis.Actual360);  // 0.0513614870373403
    Financial.Yield(new DateTime(2014,09,09), new DateTime(2014,10,20), 5.25/100, 100.305, 100, Frequency.SemiAnnual, DayCountBasis.Actual360); // 0.0514348695758675

**Comment by luajalla** [comment]
The reason is that in general case you need to find numerical solution, which doesn't match because of the different root finding algos (which might be improved though). 
So the differences in functions like rate, yield etc are expected.

**Comment by cpell** [comment]
I know slight differences are expected. I have compared to excel on a few thousand sample operations and the difference was very very small, but these are off by over 200 basis points and I can't figure out what it is about them that is making them so far off. Is this large of a difference expected?

**Comment by luajalla** [comment]
No, I'd say that's too much. Maybe the initial guess (which is 5% by default) is too off, that'd need a closer look.

**Comment by cpell** [comment]
I revisited this issue after seeing https://github.com/fsprojects/ExcelFinancialFunctions/issues/8

This issue seems partially fixed by the travis build. However, the number still does not quite match excel in my example above unless you use DayCountBasis.ActualActual and leave excel on Actual/360. 

This mismatch only occurs when the settlement date is in the last period.

**Comment by cpell** [comment]
fixed in https://github.com/fsprojects/ExcelFinancialFunctions/commit/2e9d9b1f22503af9f1b2a4d503ff3cbf06455e2c which for some reason was never merged into master. Made a pull request.
