### ISSUE TITLE
Yield function returns YTM when the date is within 6 months.  

### ISSUE THREAD

**Issue by paigeNOTRS** [fsprojects/ExcelFinancialFunctions#8]
This works different from Excel.  In Excel the following returns -0.67429 but using the FinancialFunctions it returns 0.04534.  Any date in the second parameter within 6 months will return a similiar value (11/15/2015 returns .04551).  

DateTime testsettle = Convert.ToDateTime("9/21/2015");
DateTime testmaturity = Convert.ToDateTime("10/15/2015");

Financial.Yield(testsettle, testmaturity, .04625, 105.124, 100, Excel.FinancialFunctions.Frequency.SemiAnnual, DayCountBasis.UsPsa30_360);

This is a really great tool and this is the final item I need to complete the project I'm working on.

**Comment by luajalla** [comment]
Looks like there's an issue with yield function and the last period before maturity (n <= 1), it doesn't take the price into account:
https://github.com/fsprojects/ExcelFinancialFunctions/blob/master/src/ExcelFinancialFunctions/bonds.fs#L69

Unfortunately I can't test the fix or release a new package, my laptop is still not repaired, but here's a travis build (yield branch):
https://travis-ci.org/fsprojects/ExcelFinancialFunctions/builds/81302367

**Comment by paigeNOTRS** [comment]
Thank you for such a quick response.  I resolved the issue on my side by using a different calculation for 1 coupon period.  I was going to post it today.  On my next update I will try the Travis branch.

The following is the solution I am using.

coupdays = Excel.FinancialFunctions.Financial.CoupDays(settle, dtPar, Frequency.SemiAnnual, DayCountBasis.UsPsa30_360);
coupdaysnc = Excel.FinancialFunctions.Financial.CoupDaysNC(settle, dtPar, Frequency.SemiAnnual, DayCountBasis.UsPsa30_360);
coupnum = Excel.FinancialFunctions.Financial.CoupNum(settle, dtPar, Frequency.SemiAnnual, DayCountBasis.UsPsa30_360);

E = coupdays;
A = coupdays - coupdaysnc;
DSR = coupdaysnc;

if (coupnum == 1)
     {
          newPar = (((ParPrce / 100 + coupon / frequency) - (dblPrice / 100 + (A / E * coupon / frequency))) / (dblPrice / 100 + (A / E * coupon / frequency))) * ((frequency * E) / DSR);
          Debug.Print(newCall.ToString());
     }
     else
     {
          newPar = Excel.FinancialFunctions.Financial.Yield(settle, dtPar, coupon, dblPrice, ParPrce, Frequency.SemiAnnual, DayCountBasis.UsPsa30_360);
     }

**Comment by jcoliz** [comment]
This issue refers to commit 2e9d9b1f22503af9f1b2a4d503ff3cbf06455e2c, which indeed looks like it did not get merged. Will leave this issue open to track.

**Comment by jcoliz** [comment]
Looks like this was actually already merged 9/21/2015, my mistake. I added an explicit test case.
